## API NBA

In [1]:
import requests
import pandas as pd
import time
import json


apikey="146f6a53-7b10-49bf-ad60-3b916f299ced"
url="https://api.balldontlie.io/v1/players"

### CONSULTA PRIMEROS 200 REGISTROS DE JUGADORES

In [2]:
def consulta_jugadores():

    jugadores=[]
    counter=0

    while len(jugadores)<200:
        try:
            respuesta =  requests.get(url, headers = {"Authorization": apikey},params = {'cursor':counter,'per_page':100})
            respuesta.status_code
            
            if respuesta.status_code != 200:
                print(f"Se produjo el error: {respuesta.status_code}")
                return None
            
            ball_players=respuesta.json()
            jugadores.extend(ball_players['data']) #me traigo toda la info dsps filtrar
                 
            counter=ball_players['meta'].get('next_cursor')
            if counter is None:
                break
        except:
            break
    return jugadores[:200]

In [3]:
datos_200_jugadores=consulta_jugadores()    #se almacena en variable el resultado de todos los datos para los 200 jugadores

In [4]:
print(len(datos_200_jugadores))             #se corrobora que hay 200 registros

200

In [5]:
full_name_team_200=[]
for p in datos_200_jugadores:
    full_name_team_200.append({'first_name': p['first_name'], 'last_name': p['last_name'], 'team': p['team']['name']})
print(full_name_team_200)

[{'first_name': 'Alex', 'last_name': 'Abrines', 'team': 'Thunder'}, {'first_name': 'Jaylen', 'last_name': 'Adams', 'team': 'Hawks'}, {'first_name': 'Steven', 'last_name': 'Adams', 'team': 'Rockets'}, {'first_name': 'Bam', 'last_name': 'Adebayo', 'team': 'Heat'}, {'first_name': 'DeVaughn', 'last_name': 'Akoon-Purcell', 'team': 'Nuggets'}, {'first_name': 'LaMarcus', 'last_name': 'Aldridge', 'team': 'Nets'}, {'first_name': 'Rawle', 'last_name': 'Alkins', 'team': 'Bulls'}, {'first_name': 'Grayson', 'last_name': 'Allen', 'team': 'Suns'}, {'first_name': 'Jarrett', 'last_name': 'Allen', 'team': 'Cavaliers'}, {'first_name': 'Al-Farouq', 'last_name': 'Aminu', 'team': 'Trail Blazers'}, {'first_name': 'Justin', 'last_name': 'Anderson', 'team': 'Pacers'}, {'first_name': 'Kyle', 'last_name': 'Anderson', 'team': 'Timberwolves'}, {'first_name': 'Ryan', 'last_name': 'Anderson', 'team': 'Pelicans'}, {'first_name': 'Ike', 'last_name': 'Anigbogu', 'team': 'Pacers'}, {'first_name': 'Giannis', 'last_name': 'Antetokounmpo', 'team': 'Bucks'}, {'first_name': 'Kostas', 'last_name': 'Antetokounmpo', 'team': 'Bulls'}, {'first_name': 'Carmelo', 'last_name': 'Anthony', 'team': 'Lakers'}, {'first_name': 'OG', 'last_name': 'Anunoby', 'team': 'Knicks'}, {'first_name': 'Ryan', 'last_name': 'Arcidiacono', 'team': 'Knicks'}, {'first_name': 'Trevor', 'last_name': 'Ariza', 'team': 'Lakers'}, {'first_name': 'D.J.', 'last_name': 'Augustin', 'team': 'Lakers'}, {'first_name': 'Deandre', 'last_name': 'Ayton', 'team': 'Lakers'}, {'first_name': 'Dwayne', 'last_name': 'Bacon', 'team': 'Lakers'}, {'first_name': 'Marvin', 'last_name': 'Bagley III', 'team': 'Mavericks'}, {'first_name': 'Ron', 'last_name': 'Baker', 'team': 'Knicks'}, {'first_name': 'Wade', 'last_name': 'Baldwin IV', 'team': 'Grizzlies'}, {'first_name': 'Lonzo', 'last_name': 'Ball', 'team': 'Cavaliers'}, {'first_name': 'Mo', 'last_name': 'Bamba', 'team': 'Jazz'}, {'first_name': 'J.J.', 'last_name': 'Barea', 'team': 'Mavericks'}, {'first_name': 'Harrison', 'last_name': 'Barnes', 'team': 'Spurs'}, {'first_name': 'Will', 'last_name': 'Barton', 'team': 'Raptors'}, {'first_name': 'Keita', 'last_name': 'Bates-Diop', 'team': 'Timberwolves'}, {'first_name': 'Nicolas', 'last_name': 'Batum', 'team': 'Clippers'}, {'first_name': 'Jerryd', 'last_name': 'Bayless', 'team': 'Bucks'}, {'first_name': 'Aron', 'last_name': 'Baynes', 'team': 'Pistons'}, {'first_name': 'Kent', 'last_name': 'Bazemore', 'team': 'Kings'}, {'first_name': 'Bradley', 'last_name': 'Beal', 'team': 'Clippers'}, {'first_name': 'Malik', 'last_name': 'Beasley', 'team': 'Pistons'}, {'first_name': 'Michael', 'last_name': 'Beasley', 'team': 'Heat'}, {'first_name': 'Marco', 'last_name': 'Belinelli', 'team': 'Spurs'}, {'first_name': 'Jordan', 'last_name': 'Bell', 'team': 'Bulls'}, {'first_name': "DeAndre'", 'last_name': 'Bembry', 'team': 'Bucks'}, {'first_name': 'Dragan', 'last_name': 'Bender', 'team': 'Suns'}, {'first_name': 'Davis', 'last_name': 'Bertans', 'team': 'Hornets'}, {'first_name': 'Patrick', 'last_name': 'Beverley', 'team': 'Bucks'}, {'first_name': 'Khem', 'last_name': 'Birch', 'team': 'Spurs'}, {'first_name': 'Jabari', 'last_name': 'Bird', 'team': 'Celtics'}, {'first_name': 'Bismack', 'last_name': 'Biyombo', 'team': 'Spurs'}, {'first_name': 'Nemanja', 'last_name': 'Bjelica', 'team': 'Warriors'}, {'first_name': 'Antonio', 'last_name': 'Blakeney', 'team': 'Bulls'}, {'first_name': 'Eric', 'last_name': 'Bledsoe', 'team': 'Trail Blazers'}, {'first_name': 'Trevon', 'last_name': 'Bluiett', 'team': 'Jazz'}, {'first_name': 'Bogdan', 'last_name': 'Bogdanovic', 'team': 'Clippers'}, {'first_name': 'Bojan', 'last_name': 'Bogdanovic', 'team': 'Knicks'}, {'first_name': 'Jonah', 'last_name': 'Bolden', 'team': '76ers'}, {'first_name': 'Isaac', 'last_name': 'Bonga', 'team': 'Raptors'}, {'first_name': 'Devin', 'last_name': 'Booker', 'team': 'Suns'}, {'first_name': 'Chris', 'last_name': 'Boucher', 'team': 'Celtics'}, {'first_name': 'Avery', 'last_name': 'Bradley', 'team': 'Lakers'}, {'first_name': 'Tony', 'last_name': 'Bradley', 'team': 'Hawks'}, {'first_name': 'Mikal', 'last_name': 'Bridges', 'team': 'Knicks'}, {'first_name': 'Miles', 'last_name': 'Bridges', 'team': 'Hornets'}, {'first_name': 'Isaiah', 'last_name': 'Briscoe', 'team': 'Magic'}, {'first_name': 'Ryan', 'last_name': 'Broekhoff', 'team': 'Mavericks'}, {'first_name': 'Malcolm', 'last_name': 'Brogdon', 'team': 'Knicks'}, {'first_name': 'Dillon', 'last_name': 'Brooks', 'team': 'Suns'}, {'first_name': 'MarShon', 'last_name': 'Brooks', 'team': 'Nets'}, {'first_name': 'Troy', 'last_name': 'Brown Jr.', 'team': 'Pistons'}, {'first_name': 'Bruce', 'last_name': 'Brown', 'team': 'Nuggets'}, {'first_name': 'Jaylen', 'last_name': 'Brown', 'team': 'Celtics'}, {'first_name': 'Lorenzo', 'last_name': 'Brown', 'team': 'Raptors'}, {'first_name': 'Sterling', 'last_name': 'Brown', 'team': 'Lakers'}, {'first_name': 'Jalen', 'last_name': 'Brunson', 'team': 'Knicks'}, {'first_name': 'Thomas', 'last_name': 'Bryant', 'team': 'Cavaliers'}, {'first_name': 'Reggie', 'last_name': 'Bullock', 'team': 'Rockets'}, {'first_name': 'Trey', 'last_name': 'Burke', 'team': 'Mavericks'}, {'first_name': 'Alec', 'last_name': 'Burks', 'team': 'Heat'}, {'first_name': 'Deonte', 'last_name': 'Burton', 'team': 'Thunder'}, {'first_name': 'Jimmy', 'last_name': 'Butler', 'team': 'Warriors'}, {'first_name': 'Jose', 'last_name': 'Calderon', 'team': 'Raptors'}, {'first_name': 'Kentavious', 'last_name': 'Caldwell-Pope', 'team': 'Grizzlies'}, {'first_name': 'Isaiah', 'last_name': 'Canaan', 'team': '76ers'}, {'first_name': 'Clint', 'last_name': 'Capela', 'team': 'Rockets'}, {'first_name': 'DeMarre', 'last_name': 'Carroll', 'team': 'Hawks'}, {'first_name': 'Wendell', 'last_name': 'Carter Jr.', 'team': 'Magic'}, {'first_name': 'Michael', 'last_name': 'Carter-Williams', 'team': 'Magic'}, {'first_name': 'Jevon', 'last_name': 'Carter', 'team': 'Magic'}, {'first_name': 'Vince', 'last_name': 'Carter', 'team': 'Raptors'}, {'first_name': 'Alex', 'last_name': 'Caruso', 'team': 'Thunder'}, {'first_name': 'Omri', 'last_name': 'Casspi', 'team': 'Kings'}, {'first_name': 'Willie', 'last_name': 'Cauley-Stein', 'team': '76ers'}, {'first_name': 'Troy', 'last_name': 'Caupain', 'team': 'Magic'}, {'first_name': 'Tyler', 'last_name': 'Cavanaugh', 'team': 'Hawks'}, {'first_name': 'Tyson', 'last_name': 'Chandler', 'team': 'Knicks'}, {'first_name': 'Wilson', 'last_name': 'Chandler', 'team': 'Nuggets'}, {'first_name': 'Joe', 'last_name': 'Chealey', 'team': 'Hornets'}, {'first_name': 'Marquese', 'last_name': 'Chriss', 'team': 'Mavericks'}, {'first_name': 'Gary', 'last_name': 'Clark', 'team': 'Pelicans'}, {'first_name': 'Ian', 'last_name': 'Clark', 'team': 'Warriors'}, {'first_name': 'Jordan', 'last_name': 'Clarkson', 'team': 'Knicks'}, {'first_name': 'John', 'last_name': 'Collins', 'team': 'Clippers'}, {'first_name': 'Zach', 'last_name': 'Collins', 'team': 'Bulls'}, {'first_name': 'Darren', 'last_name': 'Collison', 'team': 'Lakers'}, {'first_name': 'Mike', 'last_name': 'Conley', 'team': 'Timberwolves'}, {'first_name': 'Pat', 'last_name': 'Connaughton', 'team': 'Hornets'}, {'first_name': 'Quinn', 'last_name': 'Cook', 'team': 'Kings'}, {'first_name': 'DeMarcus', 'last_name': 'Cousins', 'team': 'Nuggets'}, {'first_name': 'Robert', 'last_name': 'Covington', 'team': '76ers'}, {'first_name': 'Allen', 'last_name': 'Crabbe', 'team': 'Trail Blazers'}, {'first_name': 'Torrey', 'last_name': 'Craig', 'team': 'Celtics'}, {'first_name': 'Jamal', 'last_name': 'Crawford', 'team': 'Clippers'}, {'first_name': 'Jae', 'last_name': 'Crowder', 'team': 'Kings'}, {'first_name': 'Dante', 'last_name': 'Cunningham', 'team': 'Pelicans'}, {'first_name': 'Seth', 'last_name': 'Curry', 'team': 'Warriors'}, {'first_name': 'Stephen', 'last_name': 'Curry', 'team': 'Warriors'}, {'first_name': 'Troy', 'last_name': 'Daniels', 'team': 'Suns'}, {'first_name': 'Anthony', 'last_name': 'Davis', 'team': 'Wizards'}, {'first_name': 'Ed', 'last_name': 'Davis', 'team': 'Cavaliers'}, {'first_name': 'Tyler', 'last_name': 'Davis', 'team': 'Thunder'}, {'first_name': 'Dewayne', 'last_name': 'Dedmon', 'team': '76ers'}, {'first_name': 'Sam', 'last_name': 'Dekker', 'team': 'Raptors'}, {'first_name': 'Angel', 'last_name': 'Delgado', 'team': 'Clippers'}, {'first_name': 'Matthew', 'last_name': 'Dellavedova', 'team': 'Kings'}, {'first_name': 'Luol', 'last_name': 'Deng', 'team': 'Bulls'}, {'first_name': 'DeMar', 'last_name': 'DeRozan', 'team': 'Kings'}, {'first_name': 'Marcus', 'last_name': 'Derrickson', 'team': 'Warriors'}, {'first_name': 'Cheick', 'last_name': 'Diallo', 'team': 'Heat'}, {'first_name': 'Hamidou', 'last_name': 'Diallo', 'team': 'Wizards'}, {'first_name': 'Gorgui', 'last_name': 'Dieng', 'team': 'Spurs'}, {'first_name': 'Spencer', 'last_name': 'Dinwiddie', 'team': 'Hornets'}, {'first_name': 'Donte', 'last_name': 'DiVincenzo', 'team': 'Timberwolves'}, {'first_name': 'Luka', 'last_name': 'Doncic', 'team': 'Lakers'}, {'first_name': 'Tyler', 'last_name': 'Dorsey', 'team': 'Mavericks'}, {'first_name': 'Damyean', 'last_name': 'Dotson', 'team': 'Knicks'}, {'first_name': 'PJ', 'last_name': 'Dozier', 'team': 'Timberwolves'}, {'first_name': 'Goran', 'last_name': 'Dragic', 'team': 'Bucks'}, {'first_name': 'Andre', 'last_name': 'Drummond', 'team': '76ers'}, {'first_name': 'Jared', 'last_name': 'Dudley', 'team': 'Suns'}, {'first_name': 'Kris', 'last_name': 'Dunn', 'team': 'Clippers'}, {'first_name': 'Kevin', 'last_name': 'Durant', 'team': 'Rockets'}, {'first_name': 'Trevon', 'last_name': 'Duval', 'team': 'Bucks'}, {'first_name': 'Vincent', 'last_name': 'Edwards', 'team': 'Rockets'}, {'first_name': 'Henry', 'last_name': 'Ellenson', 'team': 'Pistons'}, {'first_name': 'Wayne', 'last_name': 'Ellington', 'team': 'Lakers'}, {'first_name': 'Joel', 'last_name': 'Embiid', 'team': '76ers'}, {'first_name': 'James', 'last_name': 'Ennis III', 'team': 'Nuggets'}, {'first_name': 'Drew', 'last_name': 'Eubanks', 'team': 'Kings'}, {'first_name': 'Jacob', 'last_name': 'Evans', 'team': 'Warriors'}, {'first_name': 'Keenan', 'last_name': 'Evans', 'team': 'Pistons'}, {'first_name': 'Tyreke', 'last_name': 'Evans', 'team': 'Kings'}, {'first_name': 'Dante', 'last_name': 'Exum', 'team': 'Mavericks'}, {'first_name': 'Kenneth', 'last_name': 'Faried', 'team': 'Nuggets'}, {'first_name': 'Derrick', 'last_name': 'Favors', 'team': 'Rockets'}, {'first_name': 'Cristiano', 'last_name': 'Felicio', 'team': 'Bulls'}, {'first_name': 'Raymond', 'last_name': 'Felton', 'team': 'Hornets'}, {'first_name': 'Terrance', 'last_name': 'Ferguson', 'team': 'Thunder'}, {'first_name': 'Yogi', 'last_name': 'Ferrell', 'team': 'Kings'}, {'first_name': 'Dorian', 'last_name': 'Finney-Smith', 'team': 'Rockets'}, {'first_name': 'Bryn', 'last_name': 'Forbes', 'team': 'Timberwolves'}, {'first_name': 'Evan', 'last_name': 'Fournier', 'team': 'Pistons'}, {'first_name': "De'Aaron", 'last_name': 'Fox', 'team': 'Spurs'}, {'first_name': 'Melvin', 'last_name': 'Frazier Jr.', 'team': 'Thunder'}, {'first_name': 'Tim', 'last_name': 'Frazier', 'team': 'Cavaliers'}, {'first_name': 'Channing', 'last_name': 'Frye', 'team': 'Suns'}, {'first_name': 'Markelle', 'last_name': 'Fultz', 'team': 'Raptors'}, {'first_name': 'Wenyen', 'last_name': 'Gabriel', 'team': 'Celtics'}, {'first_name': 'Danilo', 'last_name': 'Gallinari', 'team': 'Bucks'}, {'first_name': 'Langston', 'last_name': 'Galloway', 'team': 'Pacers'}, {'first_name': 'Marc', 'last_name': 'Gasol', 'team': 'Grizzlies'}, {'first_name': 'Pau', 'last_name': 'Gasol', 'team': 'Lakers'}, {'first_name': 'Rudy', 'last_name': 'Gay', 'team': 'Warriors'}, {'first_name': 'Paul', 'last_name': 'George', 'team': '76ers'}, {'first_name': 'Taj', 'last_name': 'Gibson', 'team': 'Grizzlies'}, {'first_name': 'Harry', 'last_name': 'Giles III', 'team': 'Kings'}, {'first_name': 'Shai', 'last_name': 'Gilgeous-Alexander', 'team': 'Thunder'}, {'first_name': 'Rudy', 'last_name': 'Gobert', 'team': 'Timberwolves'}, {'first_name': 'Aaron', 'last_name': 'Gordon', 'team': 'Nuggets'}, {'first_name': 'Eric', 'last_name': 'Gordon', 'team': '76ers'}, {'first_name': 'Marcin', 'last_name': 'Gortat', 'team': 'Wizards'}, {'first_name': "Devonte'", 'last_name': 'Graham', 'team': 'Trail Blazers'}, {'first_name': 'Treveon', 'last_name': 'Graham', 'team': 'Hornets'}, {'first_name': 'Jerami', 'last_name': 'Grant', 'team': 'Trail Blazers'}, {'first_name': 'Jerian', 'last_name': 'Grant', 'team': 'Bulls'}, {'first_name': 'Danny', 'last_name': 'Green', 'team': '76ers'}, {'first_name': 'Draymond', 'last_name': 'Green', 'team': 'Warriors'}, {'first_name': 'Gerald', 'last_name': 'Green', 'team': 'Celtics'}, {'first_name': 'JaMychal', 'last_name': 'Green', 'team': 'Warriors'}, {'first_name': 'Jeff', 'last_name': 'Green', 'team': 'Rockets'}, {'first_name': 'Blake', 'last_name': 'Griffin', 'team': 'Celtics'}, {'first_name': 'Daniel', 'last_name': 'Hamilton', 'team': 'Hawks'}, {'first_name': 'Tim', 'last_name': 'Hardaway Jr.', 'team': 'Nuggets'}, {'first_name': 'James', 'last_name': 'Harden', 'team': 'Cavaliers'}, {'first_name': 'Maurice', 'last_name': 'Harkless', 'team': 'Kings'}, {'first_name': 'Montrezl', 'last_name': 'Harrell', 'team': '76ers'}, {'first_name': 'Devin', 'last_name': 'Harris', 'team': 'Mavericks'}, {'first_name': 'Gary', 'last_name': 'Harris', 'team': 'Bucks'}, {'first_name': 'Joe', 'last_name': 'Harris', 'team': 'Pistons'}, {'first_name': 'Andrew', 'last_name': 'Harrison', 'team': 'Grizzlies'}, {'first_name': 'Shaquille', 'last_name': 'Harrison', 'team': 'Grizzlies'}, {'first_name': 'Tobias', 'last_name': 'Harris', 'team': 'Pistons'}]

In [6]:
df_200_jugadores=pd.DataFrame(full_name_team_200)

In [7]:
df_200_jugadores

    first_name      last_name       team
0         Alex        Abrines    Thunder
1       Jaylen          Adams      Hawks
2       Steven          Adams    Rockets
3          Bam        Adebayo       Heat
4     DeVaughn  Akoon-Purcell    Nuggets
..         ...            ...        ...
195       Gary         Harris      Bucks
196        Joe         Harris    Pistons
197     Andrew       Harrison  Grizzlies
198  Shaquille       Harrison  Grizzlies
199     Tobias         Harris    Pistons

[200 rows x 3 columns]

### CONSULTA CON TIME PARA EVITAR "ERROR 429" AL CONSULTAR JUGADORES (TOTAL)

In [8]:
import time 
def consulta_jugadores_total():

    jugadores=[]
    counter=0

    while True:
        try:
            respuesta =  requests.get(url, headers = {"Authorization": apikey},params = {'cursor':counter,'per_page':100})
            respuesta.status_code
                
            if respuesta.status_code != 200:
                print(f"Se produjo el error: {respuesta.status_code}")
                return None
                
            ball_players=respuesta.json()
            jugadores.extend(ball_players['data']) #me traigo toda la info dsps filtrar
                 
            counter=ball_players['meta'].get('next_cursor')
            if counter is None:
                break

            time.sleep(25)

        except:
            break

    return jugadores

In [9]:
lista_completa_jugadores=consulta_jugadores_total()

In [10]:
print(len(lista_completa_jugadores))

900

In [127]:
lista_completa_jugadores[-1]

{'id': 17895912,
 'first_name': 'Ahmad',
 'last_name': 'Caver',
 'position': 'G',
 'height': '6-2',
 'weight': '174',
 'jersey_number': None,
 'college': 'Old Dominion',
 'country': 'USA',
 'draft_year': 2019,
 'draft_round': None,
 'draft_number': None,
 'team': {'id': 12,
  'conference': 'East',
  'division': 'Central',
  'city': 'Indiana',
  'name': 'Pacers',
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND'}}

### CONSULTA DE INFORMACIÓN DE EQUIPOS

In [44]:
url="https://api.balldontlie.io/v1/teams"
apikey="146f6a53-7b10-49bf-ad60-3b916f299ced"

def consultar_equipos():
    counter=0
    equipos=[]
    respuesta =  requests.get(url, headers = {"Authorization": apikey})
    respuesta.status_code
            
    if respuesta.status_code != 200:
        print(f"Se produjo el error: {respuesta.status_code}")
        return None
            
    ball_teams=respuesta.json()
    equipos.extend(ball_teams['data']) 
    print(json.dumps(equipos,indent=2, ensure_ascii=False))             
    return equipos

In [45]:
data_equipos=consultar_equipos()

[
  {
    "id": 1,
    "conference": "East",
    "division": "Southeast",
    "city": "Atlanta",
    "name": "Hawks",
    "full_name": "Atlanta Hawks",
    "abbreviation": "ATL"
  },
  {
    "id": 2,
    "conference": "East",
    "division": "Atlantic",
    "city": "Boston",
    "name": "Celtics",
    "full_name": "Boston Celtics",
    "abbreviation": "BOS"
  },
  {
    "id": 3,
    "conference": "East",
    "division": "Atlantic",
    "city": "Brooklyn",
    "name": "Nets",
    "full_name": "Brooklyn Nets",
    "abbreviation": "BKN"
  },
  {
    "id": 4,
    "conference": "East",
    "division": "Southeast",
    "city": "Charlotte",
    "name": "Hornets",
    "full_name": "Charlotte Hornets",
    "abbreviation": "CHA"
  },
  {
    "id": 5,
    "conference": "East",
    "division": "Central",
    "city": "Chicago",
    "name": "Bulls",
    "full_name": "Chicago Bulls",
    "abbreviation": "CHI"
  },
  {
    "id": 6,
    "conference": "East",
    "division": "Central",
    "city": "Cleveland",
    "name": "Cavaliers",
    "full_name": "Cleveland Cavaliers",
    "abbreviation": "CLE"
  },
  {
    "id": 7,
    "conference": "West",
    "division": "Southwest",
    "city": "Dallas",
    "name": "Mavericks",
    "full_name": "Dallas Mavericks",
    "abbreviation": "DAL"
  },
  {
    "id": 8,
    "conference": "West",
    "division": "Northwest",
    "city": "Denver",
    "name": "Nuggets",
    "full_name": "Denver Nuggets",
    "abbreviation": "DEN"
  },
  {
    "id": 9,
    "conference": "East",
    "division": "Central",
    "city": "Detroit",
    "name": "Pistons",
    "full_name": "Detroit Pistons",
    "abbreviation": "DET"
  },
  {
    "id": 10,
    "conference": "West",
    "division": "Pacific",
    "city": "Golden State",
    "name": "Warriors",
    "full_name": "Golden State Warriors",
    "abbreviation": "GSW"
  },
  {
    "id": 11,
    "conference": "West",
    "division": "Southwest",
    "city": "Houston",
    "name": "Rockets",
    "full_name": "Houston Rockets",
    "abbreviation": "HOU"
  },
  {
    "id": 12,
    "conference": "East",
    "division": "Central",
    "city": "Indiana",
    "name": "Pacers",
    "full_name": "Indiana Pacers",
    "abbreviation": "IND"
  },
  {
    "id": 13,
    "conference": "West",
    "division": "Pacific",
    "city": "LA",
    "name": "Clippers",
    "full_name": "LA Clippers",
    "abbreviation": "LAC"
  },
  {
    "id": 14,
    "conference": "West",
    "division": "Pacific",
    "city": "Los Angeles",
    "name": "Lakers",
    "full_name": "Los Angeles Lakers",
    "abbreviation": "LAL"
  },
  {
    "id": 15,
    "conference": "West",
    "division": "Southwest",
    "city": "Memphis",
    "name": "Grizzlies",
    "full_name": "Memphis Grizzlies",
    "abbreviation": "MEM"
  },
  {
    "id": 16,
    "conference": "East",
    "division": "Southeast",
    "city": "Miami",
    "name": "Heat",
    "full_name": "Miami Heat",
    "abbreviation": "MIA"
  },
  {
    "id": 17,
    "conference": "East",
    "division": "Central",
    "city": "Milwaukee",
    "name": "Bucks",
    "full_name": "Milwaukee Bucks",
    "abbreviation": "MIL"
  },
  {
    "id": 18,
    "conference": "West",
    "division": "Northwest",
    "city": "Minnesota",
    "name": "Timberwolves",
    "full_name": "Minnesota Timberwolves",
    "abbreviation": "MIN"
  },
  {
    "id": 19,
    "conference": "West",
    "division": "Southwest",
    "city": "New Orleans",
    "name": "Pelicans",
    "full_name": "New Orleans Pelicans",
    "abbreviation": "NOP"
  },
  {
    "id": 20,
    "conference": "East",
    "division": "Atlantic",
    "city": "New York",
    "name": "Knicks",
    "full_name": "New York Knicks",
    "abbreviation": "NYK"
  },
  {
    "id": 21,
    "conference": "West",
    "division": "Northwest",
    "city": "Oklahoma City",
    "name": "Thunder",
    "full_name": "Oklahoma City Thunder",
    "abbreviation": "OKC"
  },
  {
    "id": 22,
    "conference": "East",
    "division": "Southeast",
    "city": "Orlando",
    "name": "Magic",
    "full_name": "Orlando Magic",
    "abbreviation": "ORL"
  },
  {
    "id": 23,
    "conference": "East",
    "division": "Atlantic",
    "city": "Philadelphia",
    "name": "76ers",
    "full_name": "Philadelphia 76ers",
    "abbreviation": "PHI"
  },
  {
    "id": 24,
    "conference": "West",
    "division": "Pacific",
    "city": "Phoenix",
    "name": "Suns",
    "full_name": "Phoenix Suns",
    "abbreviation": "PHX"
  },
  {
    "id": 25,
    "conference": "West",
    "division": "Northwest",
    "city": "Portland",
    "name": "Trail Blazers",
    "full_name": "Portland Trail Blazers",
    "abbreviation": "POR"
  },
  {
    "id": 26,
    "conference": "West",
    "division": "Pacific",
    "city": "Sacramento",
    "name": "Kings",
    "full_name": "Sacramento Kings",
    "abbreviation": "SAC"
  },
  {
    "id": 27,
    "conference": "West",
    "division": "Southwest",
    "city": "San Antonio",
    "name": "Spurs",
    "full_name": "San Antonio Spurs",
    "abbreviation": "SAS"
  },
  {
    "id": 28,
    "conference": "East",
    "division": "Atlantic",
    "city": "Toronto",
    "name": "Raptors",
    "full_name": "Toronto Raptors",
    "abbreviation": "TOR"
  },
  {
    "id": 29,
    "conference": "West",
    "division": "Northwest",
    "city": "Utah",
    "name": "Jazz",
    "full_name": "Utah Jazz",
    "abbreviation": "UTA"
  },
  {
    "id": 30,
    "conference": "East",
    "division": "Southeast",
    "city": "Washington",
    "name": "Wizards",
    "full_name": "Washington Wizards",
    "abbreviation": "WAS"
  },
  {
    "id": 37,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Chicago Stags",
    "full_name": "Chicago Stags",
    "abbreviation": "CHS"
  },
  {
    "id": 38,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "St. Louis Bombers",
    "full_name": "St. Louis Bombers",
    "abbreviation": "BOM"
  },
  {
    "id": 39,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Cleveland Rebels",
    "full_name": "Cleveland Rebels",
    "abbreviation": "CLR"
  },
  {
    "id": 40,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Detroit Falcons",
    "full_name": "Detroit Falcons",
    "abbreviation": "DEF"
  },
  {
    "id": 41,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Toronto Huskies",
    "full_name": "Toronto Huskies",
    "abbreviation": "HUS"
  },
  {
    "id": 42,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Washington Capitols",
    "full_name": "Washington Capitols",
    "abbreviation": "WAS"
  },
  {
    "id": 43,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Providence Steamrollers",
    "full_name": "Providence Steamrollers",
    "abbreviation": "PRO"
  },
  {
    "id": 44,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Pittsburgh Ironmen",
    "full_name": "Pittsburgh Ironmen",
    "abbreviation": "PIT"
  },
  {
    "id": 45,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Baltimore Bullets",
    "full_name": "Baltimore Bullets",
    "abbreviation": "BAL"
  },
  {
    "id": 46,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Indianapolis Jets",
    "full_name": "Indianapolis Jets",
    "abbreviation": "JET"
  },
  {
    "id": 47,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Anderson Packers",
    "full_name": "Anderson Packers",
    "abbreviation": "AND"
  },
  {
    "id": 48,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Waterloo Hawks",
    "full_name": "Waterloo Hawks",
    "abbreviation": "WAT"
  },
  {
    "id": 49,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Indianapolis Olympians",
    "full_name": "Indianapolis Olympians",
    "abbreviation": "INO"
  },
  {
    "id": 50,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Denver Nuggets",
    "full_name": "Denver Nuggets",
    "abbreviation": "DN"
  },
  {
    "id": 51,
    "conference": "    ",
    "division": "",
    "city": "",
    "name": "Sheboygan Redskins",
    "full_name": "Sheboygan Redskins",
    "abbreviation": "SHE"
  }
]

In [43]:
len(data_equipos)

45

In [46]:
df=pd.DataFrame(data_equipos)

In [47]:
df

,id,conference,division,city,name,full_name,abbreviation
0,1,East,Southeast,Atlanta,Hawks,Atlanta Hawks,ATL
1,2,East,Atlantic,Boston,Celtics,Boston Celtics,BOS
2,3,East,Atlantic,Brooklyn,Nets,Brooklyn Nets,BKN
3,4,East,Southeast,Charlotte,Hornets,Charlotte Hornets,CHA
4,5,East,Central,Chicago,Bulls,Chicago Bulls,CHI
5,6,East,Central,Cleveland,Cavaliers,Cleveland Cavaliers,CLE
6,7,West,Southwest,Dallas,Mavericks,Dallas Mavericks,DAL
7,8,West,Northwest,Denver,Nuggets,Denver Nuggets,DEN
8,9,East,Central,Detroit,Pistons,Detroit Pistons,DET
9,10,West,Pacific,Golden State,Warriors,Golden State Warriors,GSW
10,11,West,Southwest,Houston,Rockets,Houston Rockets,HOU
11,12,East,Central,Indiana,Pacers,Indiana Pacers,IND
12,13,West,Pacific,LA,Clippers,LA Clippers,LAC
13,14,West,Pacific,Los Angeles,Lakers,Los Angeles Lakers,LAL
14,15,West,Southwest,Memphis,Grizzlies,Memphis Grizzlies,MEM
15,16,East,Southeast,Miami,Heat,Miami Heat,MIA
16,17,East,Central,Milwaukee,Bucks,Milwaukee Bucks,MIL
17,18,West,Northwest,Minnesota,Timberwolves,Minnesota Timberwolves,MIN
18,19,West,Southwest,New Orleans,Pelicans,New Orleans Pelicans,NOP
19,20,East,Atlantic,New York,Knicks,New York Knicks,NYK
20,21,West,Northwest,Oklahoma City,Thunder,Oklahoma City Thunder,OKC
21,22,East,Southeast,Orlando,Magic,Orlando Magic,ORL
22,23,East,Atlantic,Philadelphia,76ers,Philadelphia 76ers,PHI
23,24,West,Pacific,Phoenix,Suns,Phoenix Suns,PHX
24,25,West,Northwest,Portland,Trail Blazers,Portland Trail Blazers,POR
25,26,West,Pacific,Sacramento,Kings,Sacramento Kings,SAC
26,27,West,Southwest,San Antonio,Spurs,San Antonio Spurs,SAS
27,28,East,Atlantic,Toronto,Raptors,Toronto Raptors,TOR
28,29,West,Northwest,Utah,Jazz,Utah Jazz,UTA
29,30,East,Southeast,Washington,Wizards,Washington Wizards,WAS
30,37,,,,Chicago Stags,Chicago Stags,CHS
31,38,,,,St. Louis Bombers,St. Louis Bombers,BOM
32,39,,,,Cleveland Rebels,Cleveland Rebels,CLR
33,40,,,,Detroit Falcons,Detroit Falcons,DEF
34,41,,,,Toronto Huskies,Toronto Huskies,HUS
35,42,,,,Washington Capitols,Washington Capitols,WAS
36,43,,,,Providence Steamrollers,Providence Steamrollers,PRO
37,44,,,,Pittsburgh Ironmen,Pittsburgh Ironmen,PIT
38,45,,,,Baltimore Bullets,Baltimore Bullets,BAL
39,46,,,,Indianapolis Jets,Indianapolis Jets,JET
40,47,,,,Anderson Packers,Anderson Packers,AND
41,48,,,,Waterloo Hawks,Waterloo Hawks,WAT
42,49,,,,Indianapolis Olympians,Indianapolis Olympians,INO
43,50,,,,Denver Nuggets,Denver Nuggets,DN
44,51,,,,Sheboygan Redskins,Sheboygan Redskins,SHE

## THE CAT API

#### CONSULTA DE IMAGENES (3 RANDOM)

In [11]:
apikey="live_YTDFF3suyOplj6vtsTBRmGuIaBgV7erQCEEGKS9BQojs1GRiQIAmNYCTpaaxwdne"
mime_type="jpg"         #formatos posibles: jpg//png//GIF
limit=3
url=f"https://api.thecatapi.com/v1/images/search?size=med&mime_types={mime_type}&format=json&has_breeds=true&order=RANDOM&page=0&limit={limit}"    #search - random image
json_type="application/json"   



def consulta_catapi():
    
    resultado=requests.get(url, headers ={'Content-Type': json_type, 'x-api-key':apikey})
    resultado.status_code

    if resultado.status_code != 200:
        print(f"No se pudo realizar la consulta, error: {resultado.status_code}.")
    else:
        kitty=resultado.json()
        print(json.dumps(kitty, indent=2, ensure_ascii=False))
        return kitty

In [12]:
kitty=consulta_catapi()

[
  {
    "breeds": [
      {
        "weight": {
          "imperial": "7 - 15",
          "metric": "3 - 7"
        },
        "id": "amis",
        "name": "Australian Mist",
        "temperament": "Lively, Social, Fun-loving, Relaxed, Affectionate",
        "origin": "Australia",
        "country_codes": "AU",
        "country_code": "AU",
        "description": "The Australian Mist thrives on human companionship. Tolerant of even the youngest of children, these friendly felines enjoy playing games and being part of the hustle and bustle of a busy household. They make entertaining companions for people of all ages, and are happy to remain indoors between dusk and dawn or to be wholly indoor pets.",
        "life_span": "12 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Spotted Mist",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 4,
        "grooming": 3,
        "health_issues": 1,
        "intelligence": 4,
        "shedding_level": 3,
        "social_needs": 4,
        "stranger_friendly": 4,
        "vocalisation": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Australian_Mist",
        "hypoallergenic": 0,
        "reference_image_id": "_6x-3TiCA"
      }
    ],
    "id": "7-1CtKMRr",
    "url": "https://cdn2.thecatapi.com/images/7-1CtKMRr.jpg",
    "width": 1800,
    "height": 1200
  },
  {
    "breeds": [
      {
        "weight": {
          "imperial": "12 - 20",
          "metric": "5 - 9"
        },
        "id": "bsho",
        "name": "British Shorthair",
        "cfa_url": "http://cfa.org/Breeds/BreedsAB/BritishShorthair.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/british-shorthair",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/british-shorthair",
        "temperament": "Affectionate, Easy Going, Gentle, Loyal, Patient, calm",
        "origin": "United Kingdom",
        "country_codes": "GB",
        "country_code": "GB",
        "description": "The British Shorthair is a very pleasant cat to have as a companion, ans is easy going and placid. The British is a fiercely loyal, loving cat and will attach herself to every one of her family members. While loving to play, she doesn't need hourly attention. If she is in the mood to play, she will find someone and bring a toy to that person. The British also plays well by herself, and thus is a good companion for single people.",
        "life_span": "12 - 17",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Highlander, Highland Straight, Britannica",
        "adaptability": 5,
        "affection_level": 4,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 2,
        "grooming": 2,
        "health_issues": 2,
        "intelligence": 3,
        "shedding_level": 4,
        "social_needs": 3,
        "stranger_friendly": 2,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 1,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/British_Shorthair",
        "hypoallergenic": 0,
        "reference_image_id": "s4wQfYoEk"
      }
    ],
    "id": "ZdhQh9wc9",
    "url": "https://cdn2.thecatapi.com/images/ZdhQh9wc9.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "breeds": [
      {
        "weight": {
          "imperial": "7 - 12",
          "metric": "3 - 5"
        },
        "id": "snow",
        "name": "Snowshoe",
        "temperament": "Affectionate, Social, Intelligent, Sweet-tempered",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description": "The Snowshoe is a vibrant, energetic, affectionate and intelligent cat. They love being around people which makes them ideal for families, and becomes unhappy when left alone for long periods of time. Usually attaching themselves to one person, they do whatever they can to get your attention.",
        "life_span": "14 - 19",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 4,
        "grooming": 3,
        "health_issues": 1,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 4,
        "stranger_friendly": 4,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Snowshoe_(cat)",
        "hypoallergenic": 0,
        "reference_image_id": "MK-sYESvO"
      }
    ],
    "id": "013-iJFrO",
    "url": "https://cdn2.thecatapi.com/images/013-iJFrO.jpg",
    "width": 2592,
    "height": 1944
  }
]

In [13]:
type(kitty)

list

In [14]:
len(kitty)

3

#### CONSULTA DE GIF (3 RANDOM)

In [106]:
url=f"https://api.thecatapi.com/v1/images/search"  
apikey="live_YTDFF3suyOplj6vtsTBRmGuIaBgV7erQCEEGKS9BQojs1GRiQIAmNYCTpaaxwdne"
cabecera= {
    'Content-Type': json_type,
    'x-api-key':apikey,
    }
parametros = {
    'limit': 3,
    'mime_types': 'gif',
    'size': 'med',
    'order': 'RANDOM'
    } # 'se elimina has_breeds': True 

def consulta_catapi_2():
    
    resultado=requests.get(url, headers=cabecera, params=parametros)
    resultado.status_code

    if resultado.status_code != 200: 
        print(f"No se pudo realizar la consulta, error: {resultado.status_code}.")
    else:
        kitty=resultado.json()
        print(json.dumps(kitty, indent=2, ensure_ascii=False))
        return kitty

In [107]:
kitty2=consulta_catapi_2()

[
  {
    "breeds": [],
    "id": "4k2",
    "url": "https://cdn2.thecatapi.com/images/4k2.gif",
    "width": 440,
    "height": 320
  },
  {
    "breeds": [],
    "id": "MTc0MTAxNw",
    "url": "https://cdn2.thecatapi.com/images/MTc0MTAxNw.gif",
    "width": 344,
    "height": 274
  },
  {
    "breeds": [],
    "id": "MTc2Mzk5OA",
    "url": "https://cdn2.thecatapi.com/images/MTc2Mzk5OA.gif",
    "width": 244,
    "height": 250
  }
]

In [33]:
len(kitty2)

3

## RED DATA API

In [283]:
url= "https://apidatos.ree.es/es/datos/generacion/estructura-generacion"
cabeceras = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Host': 'apidatos.ree.es'
}
parametros = {
    'start_date':'2021-01-01T00:00',
    'end_date':'2022-12-31T23:59',
    'time_trunc':'month',
    'geo_limit':'nacional'
    }

def consultar_electric_system():
    respuesta=requests.get(url, headers=cabeceras,params=parametros)
    respuesta.status_code

    if respuesta.status_code !=200:
        print(f"No se pudo realizar la consulta, error: {respuesta.status_code}.")
    else:
        datos=respuesta.json()
        datos_e=datos['included']
        print(json.dumps(datos_e, indent=2, ensure_ascii=False))
        return datos_e

In [284]:
energia=consultar_electric_system()

[
  {
    "type": "Hidráulica",
    "id": "10288",
    "groupId": "1",
    "attributes": {
      "title": "Hidráulica",
      "description": null,
      "color": "#0090d1",
      "icon": null,
      "type": "Renovable",
      "magnitude": null,
      "composite": false,
      "last-update": "2022-01-11T09:21:23.000+01:00",
      "values": [
        {
          "value": 4057346.783,
          "percentage": 0.16916224016458922,
          "datetime": "2021-01-01T00:00:00.000+01:00"
        },
        {
          "value": 4517602.492,
          "percentage": 0.21789328370882452,
          "datetime": "2021-02-01T00:00:00.000+01:00"
        },
        {
          "value": 3715416.012,
          "percentage": 0.17069505725902084,
          "datetime": "2021-03-01T00:00:00.000+01:00"
        },
        {
          "value": 2745019.022,
          "percentage": 0.1390116395178189,
          "datetime": "2021-04-01T00:00:00.000+02:00"
        },
        {
          "value": 2159483.245,
          "percentage": 0.10673195097555943,
          "datetime": "2021-05-01T00:00:00.000+02:00"
        },
        {
          "value": 2182252.545,
          "percentage": 0.11044858200229404,
          "datetime": "2021-06-01T00:00:00.000+02:00"
        },
        {
          "value": 2209464.624,
          "percentage": 0.09898647754534948,
          "datetime": "2021-07-01T00:00:00.000+02:00"
        },
        {
          "value": 1883260.803,
          "percentage": 0.08789791066639682,
          "datetime": "2021-08-01T00:00:00.000+02:00"
        },
        {
          "value": 1396698.883,
          "percentage": 0.06789758792766507,
          "datetime": "2021-09-01T00:00:00.000+02:00"
        },
        {
          "value": 1023215.446,
          "percentage": 0.05015140133470104,
          "datetime": "2021-10-01T00:00:00.000+02:00"
        },
        {
          "value": 1199445.532,
          "percentage": 0.05257292216671374,
          "datetime": "2021-11-01T00:00:00.000+01:00"
        },
        {
          "value": 2536803.672,
          "percentage": 0.10746721829503192,
          "datetime": "2021-12-01T00:00:00.000+01:00"
        },
        {
          "value": 2085857.451,
          "percentage": 0.0865979014431461,
          "datetime": "2022-01-01T00:00:00.000+01:00"
        },
        {
          "value": 1174970.17,
          "percentage": 0.05639231065537004,
          "datetime": "2022-02-01T00:00:00.000+01:00"
        },
        {
          "value": 1775478.144,
          "percentage": 0.07892461852124848,
          "datetime": "2022-03-01T00:00:00.000+01:00"
        },
        {
          "value": 1802751.588,
          "percentage": 0.08409999181045708,
          "datetime": "2022-04-01T00:00:00.000+02:00"
        },
        {
          "value": 1923714.557,
          "percentage": 0.08841221262000502,
          "datetime": "2022-05-01T00:00:00.000+02:00"
        },
        {
          "value": 1192915.008,
          "percentage": 0.051898346939567054,
          "datetime": "2022-06-01T00:00:00.000+02:00"
        },
        {
          "value": 1045015.928,
          "percentage": 0.03987332754831628,
          "datetime": "2022-07-01T00:00:00.000+02:00"
        },
        {
          "value": 973565.249,
          "percentage": 0.0390261951767793,
          "datetime": "2022-08-01T00:00:00.000+02:00"
        },
        {
          "value": 1154833.141,
          "percentage": 0.04943333542177474,
          "datetime": "2022-09-01T00:00:00.000+02:00"
        },
        {
          "value": 719585.021,
          "percentage": 0.033358888784469784,
          "datetime": "2022-10-01T00:00:00.000+02:00"
        },
        {
          "value": 1311831.73,
          "percentage": 0.061993014441665543,
          "datetime": "2022-11-01T00:00:00.000+01:00"
        },
        {
          "value": 2750595.903,
          "percentage": 0.12649085509598357,
          "datetime": "2022-12-01T00:00:00.000+01:00"
        }
      ]
    }
  },
  {
    "type": "Nuclear",
    "id": "1446",
    "groupId": "1",
    "attributes": {
      "title": "Nuclear",
      "description": null,
      "color": "#464394",
      "icon": null,
      "type": "No-Renovable",
      "magnitude": null,
      "composite": false,
      "last-update": "2023-11-28T14:44:18.000+01:00",
      "values": [
        {
          "value": 5199740.516,
          "percentage": 0.21679185955871424,
          "datetime": "2021-01-01T00:00:00.000+01:00"
        },
        {
          "value": 4358515.107,
          "percentage": 0.21022017108422222,
          "datetime": "2021-02-01T00:00:00.000+01:00"
        },
        {
          "value": 4833065.002,
          "percentage": 0.2220425127599304,
          "datetime": "2021-03-01T00:00:00.000+01:00"
        },
        {
          "value": 4197332.93,
          "percentage": 0.2125588666326665,
          "datetime": "2021-04-01T00:00:00.000+02:00"
        },
        {
          "value": 4373250.552,
          "percentage": 0.21614687893533632,
          "datetime": "2021-05-01T00:00:00.000+02:00"
        },
        {
          "value": 3684377.943,
          "percentage": 0.18647443912816192,
          "datetime": "2021-06-01T00:00:00.000+02:00"
        },
        {
          "value": 5119328.941,
          "percentage": 0.2293516419141157,
          "datetime": "2021-07-01T00:00:00.000+02:00"
        },
        {
          "value": 5151337.803,
          "percentage": 0.2404297000708759,
          "datetime": "2021-08-01T00:00:00.000+02:00"
        },
        {
          "value": 4890618.221,
          "percentage": 0.2377471513170734,
          "datetime": "2021-09-01T00:00:00.000+02:00"
        },
        {
          "value": 4748364.457,
          "percentage": 0.23273410550766532,
          "datetime": "2021-10-01T00:00:00.000+02:00"
        },
        {
          "value": 3562254.807,
          "percentage": 0.15613726485281776,
          "datetime": "2021-11-01T00:00:00.000+01:00"
        },
        {
          "value": 3922833.452,
          "percentage": 0.16618392805650972,
          "datetime": "2021-12-01T00:00:00.000+01:00"
        },
        {
          "value": 5048424.951,
          "percentage": 0.20959390400347053,
          "datetime": "2022-01-01T00:00:00.000+01:00"
        },
        {
          "value": 4771058.269,
          "percentage": 0.22898538782505437,
          "datetime": "2022-02-01T00:00:00.000+01:00"
        },
        {
          "value": 4766690.052,
          "percentage": 0.21189176292283893,
          "datetime": "2022-03-01T00:00:00.000+01:00"
        },
        {
          "value": 4414715.447,
          "percentage": 0.2059504678346168,
          "datetime": "2022-04-01T00:00:00.000+02:00"
        },
        {
          "value": 4066355.361,
          "percentage": 0.18688608112727886,
          "datetime": "2022-05-01T00:00:00.000+02:00"
        },
        {
          "value": 4459458.308,
          "percentage": 0.19401090008846525,
          "datetime": "2022-06-01T00:00:00.000+02:00"
        },
        {
          "value": 5073367.597,
          "percentage": 0.19357795661100707,
          "datetime": "2022-07-01T00:00:00.000+02:00"
        },
        {
          "value": 5122046.93,
          "percentage": 0.20532162934135628,
          "datetime": "2022-08-01T00:00:00.000+02:00"
        },
        {
          "value": 4847367.123,
          "percentage": 0.20749449976491643,
          "datetime": "2022-09-01T00:00:00.000+02:00"
        },
        {
          "value": 4021338.375,
          "percentage": 0.18642325187636924,
          "datetime": "2022-10-01T00:00:00.000+02:00"
        },
        {
          "value": 4182092.888,
          "percentage": 0.19763246983069296,
          "datetime": "2022-11-01T00:00:00.000+01:00"
        },
        {
          "value": 5161189.944,
          "percentage": 0.23734614329110035,
          "datetime": "2022-12-01T00:00:00.000+01:00"
        }
      ]
    }
  },
  {
    "type": "Carbón",
    "id": "10289",
    "groupId": "1",
    "attributes": {
      "title": "Carbón",
      "description": null,
      "color": "#993300",
      "icon": null,
      "type": "No-Renovable",
      "magnitude": null,
      "composite": false,
      "last-update": "2022-01-11T09:21:29.000+01:00",
      "values": [
        {
          "value": 557975.979,
          "percentage": 0.023263593578234647,
          "datetime": "2021-01-01T00:00:00.000+01:00"
        },
        {
          "value": 176266.719,
          "percentage": 0.00850170732805826,
          "datetime": "2021-02-01T00:00:00.000+01:00"
        },
        {
          "value": 242138.946,
          "percentage": 0.01112443966398801,
          "datetime": "2021-03-01T00:00:00.000+01:00"
        },
        {
          "value": 270100.026,
          "percentage": 0.013678246725120696,
          "datetime": "2021-04-01T00:00:00.000+02:00"
        },
        {
          "value": 331931.113,
          "percentage": 0.016405617113264,
          "datetime": "2021-05-01T00:00:00.000+02:00"
        },
        {
          "value": 473579.232,
          "percentage": 0.023968882410049124,
          "datetime": "2021-06-01T00:00:00.000+02:00"
        },
        {
          "value": 311102.33,
          "percentage": 0.013937731099355637,
          "datetime": "2021-07-01T00:00:00.000+02:00"
        },
        {
          "value": 319182.668,
          "percentage": 0.014897293881672848,
          "datetime": "2021-08-01T00:00:00.000+02:00"
        },
        {
          "value": 477087.202,
          "percentage": 0.02319259408110997,
          "datetime": "2021-09-01T00:00:00.000+02:00"
        },
        {
          "value": 527419.848,
          "percentage": 0.025850708736207862,
          "datetime": "2021-10-01T00:00:00.000+02:00"
        },
        {
          "value": 576437.576,
          "percentage": 0.025265847434093523,
          "datetime": "2021-11-01T00:00:00.000+01:00"
        },
        {
          "value": 719926.374,
          "percentage": 0.03049841248850447,
          "datetime": "2021-12-01T00:00:00.000+01:00"
        },
        {
          "value": 709963.219,
          "percentage": 0.029475324326571517,
          "datetime": "2022-01-01T00:00:00.000+01:00"
        },
        {
          "value": 568629.528,
          "percentage": 0.027291189010179243,
          "datetime": "2022-02-01T00:00:00.000+01:00"
        },
        {
          "value": 705226.125,
          "percentage": 0.03134913435850399,
          "datetime": "2022-03-01T00:00:00.000+01:00"
        },
        {
          "value": 691004.601,
          "percentage": 0.03223598951287578,
          "datetime": "2022-04-01T00:00:00.000+02:00"
        },
        {
          "value": 527154.558,
          "percentage": 0.024227555328262127,
          "datetime": "2022-05-01T00:00:00.000+02:00"
        },
        {
          "value": 833036.37,
          "percentage": 0.03624165196481253,
          "datetime": "2022-06-01T00:00:00.000+02:00"
        },
        {
          "value": 882232.497,
          "percentage": 0.03366220971767807,
          "datetime": "2022-07-01T00:00:00.000+02:00"
        },
        {
          "value": 819592.534,
          "percentage": 0.03285406728534034,
          "datetime": "2022-08-01T00:00:00.000+02:00"
        },
        {
          "value": 632066.719,
          "percentage": 0.02705600057702851,
          "datetime": "2022-09-01T00:00:00.000+02:00"
        },
        {
          "value": 380331.127,
          "percentage": 0.017631584033299456,
          "datetime": "2022-10-01T00:00:00.000+02:00"
        },
        {
          "value": 319685.821,
          "percentage": 0.015107339809541508,
          "datetime": "2022-11-01T00:00:00.000+01:00"
        },
        {
          "value": 693262.892,
          "percentage": 0.031880879310462094,
          "datetime": "2022-12-01T00:00:00.000+01:00"
        }
      ]
    }
  },
  {
    "type": "Fuel + Gas",
    "id": "10290",
    "groupId": "1",
    "attributes": {
      "title": "Fuel + Gas",
      "description": null,
      "color": "#ba0f16",
      "icon": null,
      "type": "No-Renovable",
      "magnitude": null,
      "composite": false,
      "last-update": "2021-08-09T10:20:10.000+02:00",
      "values": [
        {
          "value": -0.001,
          "percentage": 4.4801114473670567e-11,
          "datetime": "2021-07-01T00:00:00.000+02:00"
        },
        {
          "value": 0,
          "percentage": 0,
          "datetime": "2021-08-01T00:00:00.000+02:00"
        },
        {
          "value": 0,
          "percentage": 0,
          "datetime": "2021-09-01T00:00:00.000+02:00"
        },
        {
          "value": 0,
          "percentage": 0,
          "datetime": "2022-09-01T00:00:00.000+02:00"
        },
        {
          "value": 0,
          "percentage": 0,
          "datetime": "2022-10-01T00:00:00.000+02:00"
        }
      ]
    }
  },
  {
    "type": "Motores diésel",
    "id": "10344",
    "groupId": "1",
    "attributes": {
      "title": "Motores diésel",
      "description": null,
      "color": "#8DA69F",
      "icon": null,
      "type": "No-Renovable",
      "magnitude": null,
      "composite": false,
      "last-update": "2021-02-08T08:24:08.000+01:00",
      "values": [
        {
          "value": 203759.973,
          "percentage": 0.008495328433097412,
          "datetime": "2021-01-01T00:00:00.000+01:00"
        },
        {
          "value": 160418.085,
          "percentage": 0.007737295029571479,
          "datetime": "2021-02-01T00:00:00.000+01:00"
        },
        {
          "value": 173283.976,
          "percentage": 0.007961078412177223,
          "datetime": "2021-03-01T00:00:00.000+01:00"
        },
        {
          "value": 187547.789,
          "percentage": 0.009497684871355314,
          "datetime": "2021-04-01T00:00:00.000+02:00"
        },
        {
          "value": 178362.3,
          "percentage": 0.008815514685545997,
          "datetime": "2021-05-01T00:00:00.000+02:00"
        },
        {
          "value": 206220.592,
          "percentage": 0.01043727593227466,
          "datetime": "2021-06-01T00:00:00.000+02:00"
        },
        {
          "value": 239576.816,
          "percentage": 0.01073330835885351,
          "datetime": "2021-07-01T00:00:00.000+02:00"
        },
        {
          "value": 258860.338,
          "percentage": 0.012081854424173075,
          "datetime": "2021-08-01T00:00:00.000+02:00"
        },
        {
          "value": 256964.192,
          "percentage": 0.01249177545206171,
          "datetime": "2021-09-01T00:00:00.000+02:00"
        },
        {
          "value": 233570.565,
          "percentage": 0.011448117980509724,
          "datetime": "2021-10-01T00:00:00.000+02:00"
        },
        {
          "value": 203062.243,
          "percentage": 0.00890042541443,
          "datetime": "2021-11-01T00:00:00.000+01:00"
        },
        {
          "value": 215797.238,
          "percentage": 0.009141869802375057,
          "datetime": "2021-12-01T00:00:00.000+01:00"
        },
        {
          "value": 210125.165,
          "percentage": 0.008723701766231011,
          "datetime": "2022-01-01T00:00:00.000+01:00"
        },
        {
          "value": 185575.526,
          "percentage": 0.00890663693379186,
          "datetime": "2022-02-01T00:00:00.000+01:00"
        },
        {
          "value": 207451.405,
          "percentage": 0.009221754183036578,
          "datetime": "2022-03-01T00:00:00.000+01:00"
        },
        {
          "value": 205100.239,
          "percentage": 0.009568111621723219,
          "datetime": "2022-04-01T00:00:00.000+02:00"
        },
        {
          "value": 215844.38,
          "percentage": 0.009920016016904924,
          "datetime": "2022-05-01T00:00:00.000+02:00"
        },
        {
          "value": 224846.99,
          "percentage": 0.009782077530319214,
          "datetime": "2022-06-01T00:00:00.000+02:00"
        },
        {
          "value": 242769.399,
          "percentage": 0.009263039448174696,
          "datetime": "2022-07-01T00:00:00.000+02:00"
        },
        {
          "value": 245672.779,
          "percentage": 0.009848003338989114,
          "datetime": "2022-08-01T00:00:00.000+02:00"
        },
        {
          "value": 216066.758,
          "percentage": 0.009248869072514288,
          "datetime": "2022-09-01T00:00:00.000+02:00"
        },
        {
          "value": 202310.788,
          "percentage": 0.009378826517833318,
          "datetime": "2022-10-01T00:00:00.000+02:00"
        },
        {
          "value": 192196.611,
          "percentage": 0.00908260336206548,
          "datetime": "2022-11-01T00:00:00.000+01:00"
        },
        {
          "value": 200241.645,
          "percentage": 0.009208454384103101,
          "datetime": "2022-12-01T00:00:00.000+01:00"
        }
      ]
    }
  },
  {
    "type": "Turbina de gas",
    "id": "1450",
    "groupId": "1",
    "attributes": {
      "title": "Turbina de gas",
      "description": null,
      "color": "#BA0F16",
      "icon": null,
      "type": "No-Renovable",
      "magnitude": null,
      "composite": false,
      "last-update": "2023-11-28T14:44:18.000+01:00",
      "values": [
        {
          "value": 28766.271,
          "percentage": 0.001199347037312797,
          "datetime": "2021-01-01T00:00:00.000+01:00"
        },
        {
          "value": 18026.13,
          "percentage": 0.0008694374206711752,
          "datetime": "2021-02-01T00:00:00.000+01:00"
        },
        {
          "value": 27904.377,
          "percentage": 0.0012819935141605628,
          "datetime": "2021-03-01T00:00:00.000+01:00"
        },
        {
          "value": 24553.477,
          "percentage": 0.0012434227472661416,
          "datetime": "2021-04-01T00:00:00.000+02:00"
        },
        {
          "value": 24916.217,
          "percentage": 0.0012314781591835876,
          "datetime": "2021-05-01T00:00:00.000+02:00"
        },
        {
          "value": 34119.217,
          "percentage": 0.00172684831795147,
          "datetime": "2021-06-01T00:00:00.000+02:00"
        },
        {
          "value": 40565.981,
          "percentage": 0.0018174011585177451,
          "datetime": "2021-07-01T00:00:00.000+02:00"
        },
        {
          "value": 47885.346,
          "percentage": 0.0022349649385961876,
          "datetime": "2021-08-01T00:00:00.000+02:00"
        },
        {
          "value": 71402.214,
          "percentage": 0.0034710689342585797,
          "datetime": "2021-09-01T00:00:00.000+02:00"
        },
        {
          "value": 46314.807,
          "percentage": 0.002270052199345143,
          "datetime": "2021-10-01T00:00:00.000+02:00"
        },
        {
          "value": 30058.985,
          "percentage": 0.0013175159993971414,
          "datetime": "2021-11-01T00:00:00.000+01:00"
        },
        {
          "value": 29066.882,
          "percentage": 0.0012313672467161008,
          "datetime": "2021-12-01T00:00:00.000+01:00"
        },
        {
          "value": 34446.764,
          "percentage": 0.0014301156929382676,
          "datetime": "2022-01-01T00:00:00.000+01:00"
        },
        {
          "value": 34328.002,
          "percentage": 0.0016475612763532236,
          "datetime": "2022-02-01T00:00:00.000+01:00"
        },
        {
          "value": 38861.629,
          "percentage": 0.0017275004225224002,
          "datetime": "2022-03-01T00:00:00.000+01:00"
        },
        {
          "value": 34572.36,
          "percentage": 0.0016128318578234272,
          "datetime": "2022-04-01T00:00:00.000+02:00"
        },
        {
          "value": 42307.777,
          "percentage": 0.0019444278580690484,
          "datetime": "2022-05-01T00:00:00.000+02:00"
        },
        {
          "value": 47734.012,

lista de diccionarios:'data','meta','included'
lista de diccionarios de tipos de energia --> 'included': 
1.key 'type'
2.key 'attributes' + key 'type' esta el valor (renovable/norenovable) 
3.key 'attributes' + key 'values' :lista de diccionarios (12) m + keys 'datetime'
4.key 'attributes' + key 'values' lista de diccionarios (12) m + keys 'value'

In [285]:
type(energia)

list

In [ ]:
tipo_energia={}
for e in energia:
    for m in e['attributes']['values']:
        tipo_energia={'tipo_energia':e['type'], 'tipo_generacion':e['attributes']['type'], 'fecha': m['datetime'], 'valor': m['value']}

In [302]:
df=pd.DataFrame(tipo_energia)

In [303]:
len(tipo_energia)

389

In [304]:
df=pd.DataFrame(tipo_energia)

In [290]:
df

,tipo_energia,tipo_generacion,fecha,valor
0,Hidráulica,Renovable,2021-01-01T00:00:00.000+01:00,4.057347e+06
1,Hidráulica,Renovable,2021-02-01T00:00:00.000+01:00,4.517602e+06
2,Hidráulica,Renovable,2021-03-01T00:00:00.000+01:00,3.715416e+06
3,Hidráulica,Renovable,2021-04-01T00:00:00.000+02:00,2.745019e+06
4,Hidráulica,Renovable,2021-05-01T00:00:00.000+02:00,2.159483e+06
...,...,...,...,...
384,Generación total,Generación total,2022-08-01T00:00:00.000+02:00,2.494646e+07
385,Generación total,Generación total,2022-09-01T00:00:00.000+02:00,2.336142e+07
386,Generación total,Generación total,2022-10-01T00:00:00.000+02:00,2.157101e+07
387,Generación total,Generación total,2022-11-01T00:00:00.000+01:00,2.116096e+07
388,Generación total,Generación total,2022-12-01T00:00:00.000+01:00,2.174541e+07

In [ ]:
url= "https://apidatos.ree.es/es/datos/generacion/estructura-generacion"
cabeceras = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Host': 'apidatos.ree.es'
}
parametros = {
    'start_date':'2011-01-01T00:00',
    'end_date':'2022-12-31T23:59',
    'time_trunc':'month',
    'geo_limit':'nacional'
    }

def consultar_electric_system2():
    respuesta=requests.get(url, headers=cabeceras,params=parametros)
    respuesta.status_code

    datos=respuesta.json()
    return datos

#### EVITA ERROR 400

In [291]:
diccionario_año = {"tipo_energia": [], "tipo_generacion": [], "fecha": [], "valor": []}

for año in range(2011, 2023): 
    url_nacional = f"https://apidatos.ree.es/es/datos/generacion/estructura-generacion?start_date={año}-01-01T00:00&end_date={año}-12-31T23:59&time_trunc=month"
    datos_año =  requests.get(url_nacional)
    json_año = datos_año.json()

    for elemento in json_año["included"]:
        for dato in elemento["attributes"]["values"]:
            diccionario_año["tipo_energia"].append(elemento["attributes"]["title"])
            diccionario_año["tipo_generacion"].append(elemento["attributes"]["type"])
            diccionario_año["valor"].append(dato["value"])
            diccionario_año["fecha"].append(dato["datetime"])

In [292]:
len(diccionario_año)

4

In [306]:
df=pd.DataFrame(diccionario_año)
df

,tipo_energia,tipo_generacion,fecha,valor
0,Hidráulica,Renovable,2011-01-01T00:00:00.000+01:00,5.119512e+06
1,Hidráulica,Renovable,2011-02-01T00:00:00.000+01:00,2.998051e+06
2,Hidráulica,Renovable,2011-03-01T00:00:00.000+01:00,3.910363e+06
3,Hidráulica,Renovable,2011-04-01T00:00:00.000+02:00,3.537938e+06
4,Hidráulica,Renovable,2011-05-01T00:00:00.000+02:00,2.797500e+06
...,...,...,...,...
2338,Generación total,Generación total,2022-08-01T00:00:00.000+02:00,2.494646e+07
2339,Generación total,Generación total,2022-09-01T00:00:00.000+02:00,2.336142e+07
2340,Generación total,Generación total,2022-10-01T00:00:00.000+02:00,2.157101e+07
2341,Generación total,Generación total,2022-11-01T00:00:00.000+01:00,2.116096e+07
2342,Generación total,Generación total,2022-12-01T00:00:00.000+01:00,2.174541e+07

In [331]:

for año in range(2011, 2023): 
    url_nacional = f"https://apidatos.ree.es/es/datos/generacion/estructura-generacion?start_date={año}-01-01T00:00&end_date={año}-12-31T23:59&time_trunc=month"
    respuesta =  requests.get(url_nacional)
    energia = respuesta.json()

tipo_energia = {
    'tipo_energia': [],
    'tipo_generacion': [],
    'fecha': [],
    'valor': []
}
for e in energia['included']:
    for m in e['attributes']['values']:
        tipo_energia['tipo_energia'].append(e['type'])
        tipo_energia['tipo_generacion'].append(e['attributes']['type'])
        tipo_energia['fecha'].append(m['datetime'])
        tipo_energia['valor'].append(m['value'])
df = pd.DataFrame(tipo_energia)

In [332]:
df

,tipo_energia,tipo_generacion,fecha,valor
0,Hidráulica,Renovable,2022-01-01T00:00:00.000+01:00,2.085857e+06
1,Hidráulica,Renovable,2022-02-01T00:00:00.000+01:00,1.174970e+06
2,Hidráulica,Renovable,2022-03-01T00:00:00.000+01:00,1.775478e+06
3,Hidráulica,Renovable,2022-04-01T00:00:00.000+02:00,1.802752e+06
4,Hidráulica,Renovable,2022-05-01T00:00:00.000+02:00,1.923715e+06
...,...,...,...,...
189,Generación total,Generación total,2022-08-01T00:00:00.000+02:00,2.494646e+07
190,Generación total,Generación total,2022-09-01T00:00:00.000+02:00,2.336142e+07
191,Generación total,Generación total,2022-10-01T00:00:00.000+02:00,2.157101e+07
192,Generación total,Generación total,2022-11-01T00:00:00.000+01:00,2.116096e+07
193,Generación total,Generación total,2022-12-01T00:00:00.000+01:00,2.174541e+07