### Módulo 2 Python +SQL: Nivel Intermedio

Importar las librerías necesarias para crear la conexión y trabajar con Pandas.
Crear la conexión a la base de datos Northwind que devuelva un mensaje de error si algo no ocurre cómo debería. //Se reemplaza por 'tienda'
Usando "information_schema" en la conexión a base de datos, extraer los nombres de las columnas de la tabla "customers" de la bases de datos "northwind".
Seleccionar todo de la tabla "customers" donde "city" sea "London" o "Seattle". Almacenar los resultados en una variable. 
Convertir los resultados del ejercicio anterior en un Dataframe (no olvidéis de poner el nombre a las columnas en el orden correcto).
Muestra las 10 primeras filas del Dataframe y las 10 últimas.
Mostrar 5 filas aleatorias del Dataframe.
¿Hay nulos en el Dataframe? El resultado debe verse para cada una de las columnas.
Mostrar los principales estadísticos.
Mostrar el nombre de las columnas del Dataframe.

In [1]:
#Librerías
import mysql.connector
from mysql.connector import errorcode
from sqlalchemy import create_engine,FLOAT, VARCHAR, INTEGER, DATE, SmallInteger
from sqlalchemy.sql.sqltypes import String
import pandas as pd

In [2]:
# Establecer conexión con MySQL
try:
    cnx=mysql.connector.connect(user='root', password='my-secret-pw', host ='127.0.0.1', database= 'tienda')
    print("Se estableció la conexión con Mysql.")
except mysql.connector.Error as err:
    print(f"No se pudo establecer la conexión. Error: {err}")

Se estableció la conexión con Mysql.

In [3]:
# Acceso a la Base de Datos 'tienda' y consulta de nombre de columnas.

try:
    mycursor=cnx.cursor()
    query_tienda='USE tienda'
    mycursor.execute(query_tienda)
    print("Se accedió a la Base de Datos 'tienda'.")
    query_info_col="SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'tienda' AND TABLE_NAME = 'customers'"
    mycursor.execute(query_info_col)
    resultado=[col[0] for col in mycursor.fetchall()]
    print(resultado)
        
except mysql.connector.Error as err:
    print(f"No se pudo acceder a la tabla. Error: {err}")

Se accedió a la Base de Datos 'tienda'.
['customer_number', 'customer_name', 'contact_last_name', 'contact_first_name', 'phone', 'address_line1', 'address_line2', 'city', 'state', 'postal_code', 'country', 'sales_rep_employee_number', 'credit_limit']

In [4]:
# Consulta de customers en ciudad de Londres o Seattle
query_1="SELECT * FROM customers WHERE city IN ('London','Seattle')"
mycursor.execute(query_1)
resultado_q1=mycursor.fetchall()
df=pd.DataFrame(resultado_q1, columns=resultado)
df

,customer_number,customer_name,contact_last_name,contact_first_name,phone,address_line1,address_line2,city,state,postal_code,country,sales_rep_employee_number,credit_limit
0,324,"Stylish Desk Decors, Co.",Brown,Ann,(171) 555-0297,35 King George,None,London,None,WX3 6FW,UK,1501,77000.00
1,489,"Double Decker Gift Stores, Ltd",Smith,Thomas,(171) 555-7555,120 Hanover Sq.,None,London,None,WA1 1DP,UK,1501,43300.00

In [5]:
# Consulta de customers
query_2="SELECT * FROM customers"
mycursor.execute(query_2)
resultado_q2=mycursor.fetchall()
df2=pd.DataFrame(resultado_q2, columns=resultado)
df2.sample(15)

,customer_number,customer_name,contact_last_name,contact_first_name,phone,address_line1,address_line2,city,state,postal_code,country,sales_rep_employee_number,credit_limit
57,282,Souveniers And Things Co.,Huxley,Adrian,+61 2 9495 8555,Monitor Money Building,815 Pacific Hwy,Chatswood,NSW,2067,Australia,1611.0,93300.00
110,471,"Australian Collectables, Ltd",Clenahan,Sean,61-9-3844-6555,7 Allen Street,NaN,Glen Waverly,Victoria,3150,Australia,1611.0,60300.00
63,307,Der Hund Imports,Andersen,Mel,030-0074555,Obere Str. 57,NaN,Berlin,NaN,12209,Germany,NaN,0.00
45,239,Collectable Mini Designs Co.,Thompson,Valarie,7605558146,361 Furth Circle,NaN,San Diego,CA,91217,USA,1166.0,105000.00
87,376,Precious Collectables,Urs,Braun,0452-076555,Hauptstr. 29,NaN,Bern,NaN,3012,Switzerland,1702.0,0.00
27,181,Vitachrome Inc.,Frick,Michael,2125551500,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,1286.0,76400.00
6,125,Havel & Zbyszek Co,Piestrzeniewicz,Zbyszek,(26) 642-7555,ul. Filtrowa 68,NaN,Warszawa,NaN,01-012,Poland,NaN,0.00
0,103,Atelier graphique,Schmitt,Carine,40.32.2555,"54, rue Royale",NaN,Nantes,NaN,44000,France,1370.0,21000.00
115,481,"Raanan Stores, Inc","Altagar,G M",Raanan,+ 972 9 959 8555,3 Hagalim Blv.,NaN,Herzlia,NaN,47625,Israel,NaN,0.00
112,475,West Coast Collectables Co.,Thompson,Steve,3105553722,3675 Furth Circle,NaN,Burbank,CA,94019,USA,1166.0,55400.00
44,237,ANG Resellers,Camino,Alejandra,(91) 745 6555,"Gran VÃ­a, 1",NaN,Madrid,NaN,28001,Spain,NaN,0.00
52,259,"Toms SpezialitÃ¤ten, Ltd",Pfalzheim,Henriette,0221-5554327,Mehrheimerstr. 369,NaN,KÃ¶ln,NaN,50739,Germany,1504.0,120400.00
102,450,The Sharp Gifts Warehouse,Frick,Sue,4085553659,3086 Ingle Ln.,NaN,San Jose,CA,94217,USA,1165.0,77600.00
101,448,Scandinavian Gift Ideas,Larsson,Martha,0695-34 6555,Ã…kergatan 24,NaN,BrÃ¤cke,NaN,S-844 67,Sweden,1504.0,116400.00
113,477,Mit VergnÃ¼gen & Co.,Moos,Hanna,0621-08555,Forsterstr. 57,NaN,Mannheim,NaN,68306,Germany,NaN,0.00

In [6]:
# Consulta de customers donde hay NULL
print("\n=== Nulos por columna ===\n=========================")
print(df2.isnull().sum())

print("\n=== Nombres de columnas ===\n===========================")
print(list(df2.columns))

=== Nulos por columna ===
=========================
customer_number                0
customer_name                  0
contact_last_name              0
contact_first_name             0
phone                          0
address_line1                  0
address_line2                100
city                           0
state                         73
postal_code                    7
country                        0
sales_rep_employee_number     22
credit_limit                   0
dtype: int64

=== Nombres de columnas ===
===========================
['customer_number', 'customer_name', 'contact_last_name', 'contact_first_name', 'phone', 'address_line1', 'address_line2', 'city', 'state', 'postal_code', 'country', 'sales_rep_employee_number', 'credit_limit']

In [7]:
print("\n=== Estadísticos principales ===\n================================")
print(df2.describe(include='all'))

=== Estadísticos principales ===
================================
        customer_number      customer_name contact_last_name  \
count        122.000000                122               122
unique              NaN                122               108
top                 NaN  Atelier graphique             Young
freq                NaN                  1                 4
mean         296.401639                NaN               NaN
std          117.077544                NaN               NaN
min          103.000000                NaN               NaN
25%          191.250000                NaN               NaN
50%          298.500000                NaN               NaN
75%          384.250000                NaN               NaN
max          496.000000                NaN               NaN

       contact_first_name       phone   address_line1 address_line2 city  \
count                 122         122             122            22  122
unique                111         121             122            21   96
top                 Julie  6175558555  54, rue Royale     Suite 101  NYC
freq                    4           2               1             2    5
mean                  NaN         NaN             NaN           NaN  NaN
std                   NaN         NaN             NaN           NaN  NaN
min                   NaN         NaN             NaN           NaN  NaN
25%                   NaN         NaN             NaN           NaN  NaN
50%                   NaN         NaN             NaN           NaN  NaN
75%                   NaN         NaN             NaN           NaN  NaN
max                   NaN         NaN             NaN           NaN  NaN

       state postal_code country  sales_rep_employee_number credit_limit
count     49         115     122                  100.00000          122
unique    18          94      28                        NaN           93
top       CA       94217     USA                        NaN         0.00
freq      11           5      36                        NaN           24
mean     NaN         NaN     NaN                 1395.94000          NaN
std      NaN         NaN     NaN                  165.67193          NaN
min      NaN         NaN     NaN                 1165.00000          NaN
25%      NaN         NaN     NaN                 1286.00000          NaN
50%      NaN         NaN     NaN                 1370.00000          NaN
75%      NaN         NaN     NaN                 1504.00000          NaN
max      NaN         NaN     NaN                 1702.00000          NaN

In [8]:
cnx.close()